name: superheroes
description: A flutter superheroes project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^6.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - .env
